# Generated by Django 6.0.3 on 2026-03-23 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0003_readarticle'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedarticle',
            name='thumbnail',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
