# Generated by Django 6.0.3 on 2026-03-23 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0004_savedarticle_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedarticle',
            name='link',
            field=models.URLField(max_length=1000),
        ),
    ]
