# Generated by Django 6.0.3 on 2026-04-06 10:42

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0006_usersettings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='feed',
            unique_together={('user', 'url')},
        ),
    ]
