# Generated by Django 6.0.3 on 2026-04-06 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0007_alter_feed_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='dark_mode',
            field=models.BooleanField(default=False),
        ),
    ]
